# Generated by Django 4.2.29 on 2026-03-28 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0005_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bill_pdf',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='For temporary roles, access expires after this date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Restricted permissions for SUBADMIN'),
        ),
        migrations.AlterField(
            model_name='areamanagerstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='areamanagerstore',
            name='manager',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'AREAMANAGER'), ('role', 'WHOLESALE_EXEC'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='managed_stores', to='pos.userprofile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HRA, travel, food etc.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PF, ESI, tax etc.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase / cost price (per kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_alert',
            field=models.DecimalField(decimal_places=3, default=5, help_text='Alert threshold in kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price for RETAIL (per kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price for WHOLESALE (per kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('ONLINE', 'Online'), ('CARD', 'Card'), ('CREDIT', 'Credit')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('SUBADMIN', 'Sub-Admin'), ('OWNER', 'Store Owner'), ('STAFF', 'Staff'), ('AREAMANAGER', 'Area Manager'), ('WHOLESALE_EXEC', 'Wholesale Executive')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='wholesaleapproval',
            name='area_manager',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'AREAMANAGER'), ('role', 'WHOLESALE_EXEC'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='approvals_given', to='pos.userprofile'),
        ),
        migrations.AlterField(
            model_name='wholesaleapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WholesaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst', models.CharField(blank=True, max_length=20)),
                ('is_credit_enabled', models.BooleanField(default=True)),
                ('credit_duration_days', models.PositiveIntegerField(default=7, help_text='Minimum 7, Max 30 days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_records', to='pos.wholesalecustomer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_record', to='pos.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='wholesale_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.wholesalecustomer'),
        ),
    ]
