# Generated by Django 4.2.29 on 2026-03-29 05:42

from django.db import migrations, models
import pos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_expense_bill_pdf_userprofile_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to=pos.models.Expense.expense_upload_path),
        ),
    ]
