# Generated by Django 4.2.29 on 2026-03-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_expense_bill_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditrecord',
            name='external_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='creditrecord',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creditrecord',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_record', to='pos.sale'),
        ),
    ]
