# Generated by Django 4.2.29 on 2026-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_creditrecord_amount_creditrecord_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Store WhatsApp number for sending bills (e.g. 919876543210)', max_length=20),
        ),
    ]
